In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [ ]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

#estimated salary is my output feature my ouptut and rest is independent features
#and hence this is a regression problem

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [5]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [7]:
geo_encoder = OneHotEncoder()
geo_encoded = geo_encoder.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=geo_encoder.get_feature_names_out(['Geography']))
data = pd.concat([data, geo_encoded_df], axis=1)
data = data.drop('Geography', axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
#save all the   pickle file
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)

with open('geo_encoder.pkl', 'wb') as f:
    pickle.dump(geo_encoder, f) 

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

with open('columns.pkl', 'wb') as f:
    pickle.dump(X.columns.tolist(), f)

ANN WITH REGRESSION PROBLEM STATEMENT

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
#build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) #output layer for regression
])

#when you don't give any activation fcuntion its linear by def . also for 
#regression linear activation function is used 

#compile the model

model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
#logs
from keras.callbacks import TensorBoard, EarlyStopping
import datetime

logs_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=logs_dir, histogram_freq=1)

In [16]:
#early stopping
#we use validation loss this time as the stopping condition
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [17]:
#train the model
history = model.fit(
    X_train, y_train,
    validation_data = (X_test, y_test),
    epochs= 100,
    callbacks = [tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 0s 730us/step - loss: 100367.2969 - mae: 100367.2969 - val_loss: 98481.5703 - val_mae: 98481.5703
Epoch 2/100
250/250 [==============================] - 0s 419us/step - loss: 99505.7812 - mae: 99505.7812 - val_loss: 96741.4922 - val_mae: 96741.4922
Epoch 3/100
250/250 [==============================] - 0s 408us/step - loss: 96501.2422 - mae: 96501.2422 - val_loss: 92350.8828 - val_mae: 92350.8828
Epoch 4/100
250/250 [==============================] - 0s 418us/step - loss: 90687.2422 - mae: 90687.2422 - val_loss: 85153.3750 - val_mae: 85153.3750
Epoch 5/100
250/250 [==============================] - 0s 408us/step - loss: 82367.4766 - mae: 82367.4766 - val_loss: 76099.0938 - val_mae: 76099.0938
Epoch 6/100
250/250 [==============================] - 0s 415us/step - loss: 72837.7031 - mae: 72837.7031 - val_loss: 66891.7422 - val_mae: 66891.7422
Epoch 7/100
250/250 [==============================] - 0s 421us/step - loss: 63950.7070 - mae: 63950.7070 - val_loss: 59418.4375 - val_mae: 59418.4375
Epoch 8/100
250/250 [==============================] - 0s 417us/step - loss: 57357.0039 - mae: 57357.0039 - val_loss: 54474.1055 - val_mae: 54474.1055
Epoch 9/100
250/250 [==============================] - 0s 419us/step - loss: 53419.2148 - mae: 53419.2148 - val_loss: 51935.1953 - val_mae: 51935.1953
Epoch 10/100
250/250 [==============================] - 0s 410us/step - loss: 51478.0742 - mae: 51478.0742 - val_loss: 51031.2422 - val_mae: 51031.2422
Epoch 11/100
250/250 [==============================] - 0s 423us/step - loss: 50718.0117 - mae: 50718.0117 - val_loss: 50736.2266 - val_mae: 50736.2266
Epoch 12/100
250/250 [==============================] - 0s 768us/step - loss: 50422.4805 - mae: 50422.4805 - val_loss: 50640.2461 - val_mae: 50640.2461
Epoch 13/100
250/250 [==============================] - 0s 497us/step - loss: 50291.0898 - mae: 50291.0898 - val_loss: 50601.3398 - val_mae: 50601.3398
Epoch 14/100
250/250 [==============================] - 0s 477us/step - loss: 50215.6914 - mae: 50215.6914 - val_loss: 50577.9492 - val_mae: 50577.9492
Epoch 15/100
250/250 [==============================] - 0s 493us/step - loss: 50151.6250 - mae: 50151.6250 - val_loss: 50548.9297 - val_mae: 50548.9297
Epoch 16/100
250/250 [==============================] - 0s 471us/step - loss: 50101.8047 - mae: 50101.8047 - val_loss: 50525.7812 - val_mae: 50525.7812
Epoch 17/100
250/250 [==============================] - 0s 610us/step - loss: 50058.6055 - mae: 50058.6055 - val_loss: 50501.7266 - val_mae: 50501.7266
Epoch 18/100
250/250 [==============================] - 0s 558us/step - loss: 50022.9102 - mae: 50022.9102 - val_loss: 50493.3594 - val_mae: 50493.3594
Epoch 19/100
250/250 [==============================] - 0s 455us/step - loss: 49983.0195 - mae: 49983.0195 - val_loss: 50472.4336 - val_mae: 50472.4336
Epoch 20/100
250/250 [==============================] - 0s 601us/step - loss: 49954.1836 - mae: 49954.1836 - val_loss: 50448.0859 - val_mae: 50448.0859
Epoch 21/100
250/250 [==============================] - 0s 471us/step - loss: 49925.2656 - mae: 49925.2656 - val_loss: 50421.7617 - val_mae: 50421.7617
Epoch 22/100
250/250 [==============================] - 0s 503us/step - loss: 49896.0898 - mae: 49896.0898 - val_loss: 50408.1836 - val_mae: 50408.1836
Epoch 23/100
250/250 [==============================] - 0s 412us/step - loss: 49871.3438 - mae: 49871.3438 - val_loss: 50400.3555 - val_mae: 50400.3555
Epoch 24/100
250/250 [==============================] - 0s 432us/step - loss: 49848.1367 - mae: 49848.1367 - val_loss: 50389.8125 - val_mae: 50389.8125
Epoch 25/100
250/250 [==============================] - 0s 453us/step - loss: 49828.9766 - mae: 49828.9766 - val_loss: 50379.6797 - val_mae: 50379.6797
Epoch 26/100
250/250 [==============================] - 0s 451us/step - loss: 49810.5234 - mae: 49810.5234 - val_loss: 50378.3633 - val_mae: 50378.3633
Epoch 27/100
250/250 [==============================] - 0s 731us/step - loss: 49791.5586 - mae: 49791.5586 - val_loss: 50362.8828 - val_mae: 50362.8828
Epoch 28/100
250/250 [==============================] - 0s 541us/step - loss: 49772.9805 - mae: 49772.9805 - val_loss: 50355.6680 - val_mae: 50355.6680
Epoch 29/100
250/250 [==============================] - 0s 478us/step - loss: 49758.1602 - mae: 49758.1602 - val_loss: 50360.6953 - val_mae: 50360.6953
Epoch 30/100
250/250 [==============================] - 0s 457us/step - loss: 49743.0508 - mae: 49743.0508 - val_loss: 50354.7773 - val_mae: 50354.7773
Epoch 31/100
250/250 [==============================] - 0s 474us/step - loss: 49728.5703 - mae: 49728.5703 - val_loss: 50347.1055 - val_mae: 50347.1055
Epoch 32/100
250/250 [==============================] - 0s 451us/step - loss: 49713.5430 - mae: 49713.5430 - val_loss: 50341.3047 - val_mae: 50341.3047
Epoch 33/100
250/250 [==============================] - 0s 460us/step - loss: 49702.8945 - mae: 49702.8945 - val_loss: 50323.0078 - val_mae: 50323.0078
Epoch 34/100
250/250 [==============================] - 0s 464us/step - loss: 49688.9219 - mae: 49688.9219 - val_loss: 50324.6641 - val_mae: 50324.6641
Epoch 35/100
250/250 [==============================] - 0s 729us/step - loss: 49674.3555 - mae: 49674.3555 - val_loss: 50309.4141 - val_mae: 50309.4141
Epoch 36/100
250/250 [==============================] - 0s 485us/step - loss: 49665.3125 - mae: 49665.3125 - val_loss: 50312.0742 - val_mae: 50312.0742
Epoch 37/100
250/250 [==============================] - 0s 468us/step - loss: 49653.4102 - mae: 49653.4102 - val_loss: 50312.6055 - val_mae: 50312.6055
Epoch 38/100
250/250 [==============================] - 0s 478us/step - loss: 49642.4062 - mae: 49642.4062 - val_loss: 50308.5391 - val_mae: 50308.5391
Epoch 39/100
250/250 [==============================] - 0s 412us/step - loss: 49635.1016 - mae: 49635.1016 - val_loss: 50304.2383 - val_mae: 50304.2383
Epoch 40/100
250/250 [==============================] - 0s 425us/step - loss: 49622.0781 - mae: 49622.0781 - val_loss: 50299.8398 - val_mae: 50299.8398
Epoch 41/100
250/250 [==============================] - 0s 415us/step - loss: 49614.1094 - mae: 49614.1094 - val_loss: 50303.2422 - val_mae: 50303.2422
Epoch 42/100
250/250 [==============================] - 0s 410us/step - loss: 49603.4844 - mae: 49603.4844 - val_loss: 50300.0156 - val_mae: 50300.0156
Epoch 43/100
250/250 [==============================] - 0s 406us/step - loss: 49594.5430 - mae: 49594.5430 - val_loss: 50306.2773 - val_mae: 50306.2773
Epoch 44/100
250/250 [==============================] - 0s 403us/step - loss: 49585.1094 - mae: 49585.1094 - val_loss: 50304.7539 - val_mae: 50304.7539
Epoch 45/100
250/250 [==============================] - 0s 405us/step - loss: 49576.0078 - mae: 49576.0078 - val_loss: 50303.9375 - val_mae: 50303.9375
Epoch 46/100
250/250 [==============================] - 0s 401us/step - loss: 49570.7148 - mae: 49570.7148 - val_loss: 50308.9961 - val_mae: 50308.9961
Epoch 47/100
250/250 [==============================] - 0s 415us/step - loss: 49563.8633 - mae: 49563.8633 - val_loss: 50298.3906 - val_mae: 50298.3906
Epoch 48/100
250/250 [==============================] - 0s 406us/step - loss: 49556.5195 - mae: 49556.5195 - val_loss: 50304.7422 - val_mae: 50304.7422
Epoch 49/100
250/250 [==============================] - 0s 402us/step - loss: 49549.8281 - mae: 49549.8281 - val_loss: 50297.3359 - val_mae: 50297.3359
Epoch 50/100
250/250 [==============================] - 0s 404us/step - loss: 49542.0469 - mae: 49542.0469 - val_loss: 50314.3008 - val_mae: 50314.3008
Epoch 51/100
250/250 [==============================] - 0s 402us/step - loss: 49533.0625 - mae: 49533.0625 - val_loss: 50304.5430 - val_mae: 50304.5430
Epoch 52/100
250/250 [==============================] - 0s 441us/step - loss: 49527.7461 - mae: 49527.7461 - val_loss: 50306.4375 - val_mae: 50306.4375
Epoch 53/100
250/250 [==============================] - 0s 404us/step - loss: 49522.6992 - mae: 49522.6992 - val_loss: 50298.6992 - val_mae: 50298.6992
Epoch 54/100
250/250 [==============================] - 0s 405us/step - loss: 49517.1562 - mae: 49517.1562 - val_loss: 50311.7461 - val_mae: 50311.7461
Epoch 55/100
250/250 [==============================] - 0s 551us/step - loss: 49509.6328 - mae: 49509.6328 - val_loss: 50321.3633 - val_mae: 50321.3633
Epoch 56/100
250/250 [==============================] - 0s 668us/step - loss: 49504.3633 - mae: 49504.3633 - val_loss: 50315.5430 - val_mae: 50315.5430
Epoch 57/100
250/250 [==============================] - 0s 475us/step - loss: 49498.5664 - mae: 49498.5664 - val_loss: 50312.2227 - val_mae: 50312.2227
Epoch 58/100
250/250 [==============================] - 0s 460us/step - loss: 49491.2734 - mae: 49491.2734 - val_loss: 50316.3086 - val_mae: 50316.3086
Epoch 59/100
250/250 [==============================] - 0s 514us/step - loss: 49486.0117 - mae: 49486.0117 - val_loss: 50313.4766 - val_mae: 50313.4766

In [ ]:
%load_ext tensorboard
%tensorboard --logdir regressionlogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6009 (pid 56604), started 0:00:04 ago. (Use '!kill 56604' to kill it.)

In [21]:
!kill 56604'

zsh:1: unmatched '

In [22]:

test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 [==============================] - 0s 217us/step - loss: 50297.3359 - mae: 50297.3359
Test Loss: 50297.3359375, Test MAE: 50297.3359375

In [23]:
model.save('salary_regression_model.h5')

/Users/kshitoki/Documents/annclassification/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(